// JhipsterBase_Vuejs/src/main/webapp/app/entities/demo/demo-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="sitenJhipsterBaseApp.demo.home.createOrEditLabel" v-text="$t('sitenJhipsterBaseApp.demo.home.createOrEditLabel')">Create or edit a Demo</h2>
                <div>
                    <div class="form-group" v-if="demo.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="demo.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sitenJhipsterBaseApp.demo.name')" for="demo-name">Name</label>
                        <input type="text" class="form-control" name="name" id="demo-name"
                            :class="{'valid': !$v.demo.name.$invalid, 'invalid': $v.demo.name.$invalid }" v-model="$v.demo.name.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('sitenJhipsterBaseApp.demo.description')" for="demo-description">Description</label>
                        <input type="text" class="form-control" name="description" id="demo-description"
                            :class="{'valid': !$v.demo.description.$invalid, 'invalid': $v.demo.description.$invalid }" v-model="$v.demo.description.$model" />
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.demo.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./demo-update.component.ts">
</script>

// JhipsterBase_Angular/src/main/webapp/app/entities/demo/demo-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IDemo, Demo } from 'app/shared/model/demo.model';
import { DemoService } from './demo.service';

@Component({
  selector: 'jhi-demo-update',
  templateUrl: './demo-update.component.html',
})
export class DemoUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    name: [],
    description: [],
  });

  constructor(protected demoService: DemoService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ demo }) => {
      this.updateForm(demo);
    });
  }

  updateForm(demo: IDemo): void {
    this.editForm.patchValue({
      id: demo.id,
      name: demo.name,
      description: demo.description,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const demo = this.createFromForm();
    if (demo.id !== undefined) {
      this.subscribeToSaveResponse(this.demoService.update(demo));
    } else {
      this.subscribeToSaveResponse(this.demoService.create(demo));
    }
  }

  private createFromForm(): IDemo {
    return {
      ...new Demo(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
      description: this.editForm.get(['description'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IDemo>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-demo-heading" jhiTranslate="sitenJhipsterBaseApp.demo.home.createOrEditLabel">Create or edit a Demo</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sitenJhipsterBaseApp.demo.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                           formControlName="name"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="sitenJhipsterBaseApp.demo.description" for="field_description">Description</label>
                    <input type="text" class="form-control" name="description" id="field_description"
                           formControlName="description"/>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
